-- MySQL Script generated by MySQL Workbench
-- Sat Dec  2 20:33:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema norotec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema norotec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `norotec` DEFAULT CHARACTER SET utf8 ;
USE `norotec` ;

-- -----------------------------------------------------
-- Table `norotec`.`TB_USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `norotec`.`TB_USUARIOS` (
  `Matricula_id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Sobrenome` VARCHAR(45) NULL,
  `Usuario` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `Cargo` VARCHAR(45) NULL,
  `Edita_Projeto` VARCHAR(45) NULL,
  `Ativo` VARCHAR(45) NULL,
  PRIMARY KEY (`Matricula_id`),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `norotec`.`TB_PROJETOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `norotec`.`TB_PROJETOS` (
  `idProjeto` INT NOT NULL AUTO_INCREMENT,
  `NomeDoProjeto` VARCHAR(45) NULL,
  `EtapaAtual` VARCHAR(45) NULL,
  `Usuario_id` INT NOT NULL,
  `PrazoProjeto` DATE NULL,
  `ObjetivosProjeto` TEXT NULL,
  `NumeroTarefas` INT NULL,
  `TipoEncerramento` VARCHAR(45) NULL,
  PRIMARY KEY (`idProjeto`),
  CONSTRAINT `Usuario_id`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `norotec`.`TB_USUARIOS` (`Matricula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `norotec`.`TB_TAREFAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `norotec`.`TB_TAREFAS` (
  `idTarefa` INT NOT NULL AUTO_INCREMENT,
  `NomeDaTarefa` VARCHAR(45) NULL,
  `Usuario_id_tarefa` INT NOT NULL,
  `SituacaoTarefa` VARCHAR(45) NULL,
  `Projeto_id` INT NOT NULL,
  `TipoTarefa` VARCHAR(45) NULL,
  `Descricao` TEXT NULL,
  `PrazoTarefa` DATE NULL,
  `Excluida` VARCHAR(45) NULL,
  PRIMARY KEY (`idTarefa`),
  CONSTRAINT `Usuario_id_tarefa`
    FOREIGN KEY (`Usuario_id_tarefa`)
    REFERENCES `norotec`.`TB_USUARIOS` (`Matricula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Projeto_id`
    FOREIGN KEY (`Projeto_id`)
    REFERENCES `norotec`.`TB_PROJETOS` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `norotec`.`TB_COMENTARIOS_PROJETOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `norotec`.`TB_COMENTARIOS_PROJETOS` (
  `idComentarioProjeto` INT NOT NULL AUTO_INCREMENT,
  `Usuario_id_comentario_proj` INT NOT NULL,
  `Data_Comentario_Projeto` DATE NULL,
  `Comentario_Projeto` TEXT NULL,
  `Projeto_id_comentario` INT NOT NULL,
  PRIMARY KEY (`idComentarioProjeto`),
  CONSTRAINT `Usuario_id_comentario_proj`
    FOREIGN KEY (`Usuario_id_comentario_proj`)
    REFERENCES `norotec`.`TB_USUARIOS` (`Matricula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Projeto_id_comentario`
    FOREIGN KEY (`Projeto_id_comentario`)
    REFERENCES `norotec`.`TB_PROJETOS` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `norotec`.`TB_COMENTARIOS_TAREFAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `norotec`.`TB_COMENTARIOS_TAREFAS` (
  `idComentarioTarefa` INT NOT NULL AUTO_INCREMENT,
  `Usuario_id_comentario_tarefa` INT NOT NULL,
  `Data_Comentario_Tarefa` DATE NULL,
  `Comentario_Tarefa` TEXT NULL,
  `Tarefa_id` INT NOT NULL,
  PRIMARY KEY (`idComentarioTarefa`),
  CONSTRAINT `Tarefa_id`
    FOREIGN KEY (`Tarefa_id`)
    REFERENCES `norotec`.`TB_TAREFAS` (`idTarefa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Usuario_id_comentario_tarefa`
    FOREIGN KEY (`Usuario_id_comentario_tarefa`)
    REFERENCES `norotec`.`TB_USUARIOS` (`Matricula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
